export const apiResponse = {
  count: 10,
  offset: 0,
  results: [
    {
      account: {
        fullname: "Leonardo Luduena",
        href: "/lle0x",
        id: 951196419444142081,
      },
      date: "2020-03-24T19:47:00+07:00",
      hashtags: ["#Python", "#DevOps"],
      likes: 0,
      replies: 0,
      retweets: 0,
      text:
        "#Page 1: Python Scripting by Pranavi Pinky https://link.medium.com/Rj4ApWYd84\u00a0",
    },
    {
      account: {
        fullname: "OOI Ocean Data Lab",
        href: "/ooidatalab",
        id: 1082344206667005952,
      },
      date: "2020-03-24T19:40:00+07:00",
      hashtags: ["#Python", "#ocean", "#data"],
      likes: 0,
      replies: 0,
      retweets: 2,
      text:
        "To kick off our new #Python P-Tuesday series, check out our tutorial on how to create and model a simple seasonal timeseries. #ocean #data-analysis  https://datalab.marine.rutgers.edu/2020/03/modeling-seasonal-data/\u00a0\u2026 pic.twitter.com/IHiltqO7Yc",
    },
    {
      account: {
        fullname: "Ivan Leung",
        href: "/urganmax",
        id: 2345532612,
      },
      date: "2020-03-24T19:36:00+07:00",
      hashtags: ["#rmarkdown", "#python"],
      likes: 0,
      replies: 0,
      retweets: 0,
      text:
        "May I suggest #rmarkdown? It supports #python chunk, and I find it more flexible in terms of figure manipulation in final render.\n\n https://rstudio.github.io/reticulate/articles/r_markdown.html\u00a0\u2026",
    },
    {
      account: {
        fullname: "Python Flux",
        href: "/pythonbot_",
        id: 726709023563747328,
      },
      date: "2020-03-24T18:54:00+07:00",
      hashtags: ["#python", "#ad"],
      likes: 0,
      replies: 0,
      retweets: 0,
      text:
        "Machine Learning for Beginners: Absolute Beginner's Guide to Understanding Machine Learning, \
        Artificial Intelligence, Python Programming, Neural Networks Concepts and Big Data\
        https://zpy.io/5f3ee856\u00a0 #python #ad",
    },
    {
      account: {
        fullname:
          "Steven Jordan\u00a0\ud83d\udc0d\u00a0\ud83d\udc68\ud83c\udffb\u200d\ud83d\udcbb",
        href: "/thepydtyper",
        id: 759386987866578944,
      },
      date: "2020-03-24T18:13:00+07:00",
      hashtags: ["#code", "#python", "#Django", "#webdev", "#100DaysOfCode"],
      likes: 2,
      replies: 0,
      retweets: 0,
      text:
        "Past the 1200th line of #code today in this Taoism #python #Django #webdev project. Only about 20 more chapters more to go! #100DaysOfCode pic.twitter.com/Ryqe5opVto",
    },
    {
      account: {
        fullname: "DamagedDolphin",
        href: "/DamagedDolphin",
        id: 1108562583924011008,
      },
      date: "2020-03-24T17:47:00+07:00",
      hashtags: ["#RaspberryPi", "#Python"],
      likes: 7,
      replies: 0,
      retweets: 0,
      text:
        "Got a P2 display to replace my two P5 displays. So much sharper. I may go through and cleanup and comment my code finally to release it.\n#RaspberryPi #Python  pic.twitter.com/NdFXNeoI5B",
    },
    {
      account: {
        fullname: "\u15f0issy\u00a0\ud83c\udf40",
        href: "/CodeHer317",
        id: 986041095820795904,
      },
      date: "2020-03-24T17:39:00+07:00",
      hashtags: ["#Python", "#homework"],
      likes: 0,
      replies: 0,
      retweets: 0,
      text: "Playing with #Python #homework pic.twitter.com/ZD5HzCWTMv",
    },
    {
      account: {
        fullname: "Fullstack Developer",
        href: "/FullstackDevJS",
        id: 931055758971752448,
      },
      date: "2020-03-24T17:00:00+07:00",
      hashtags: [
        "#Fullstack",
        "#Javascript",
        "#Angular",
        "#DevTips",
        "#React",
        "#Php",
        "#Python",
        "#Rails",
        "#ROR",
        "#Datascience",
      ],
      likes: 20,
      replies: 0,
      retweets: 11,
      text:
        "How Netflix works: the (Hugely Simplified) Complex Stuff that Happens Every Time You Hit Play #Fullstack #Javascript #Angular #DevTips #React #Php #Python #Rails #ROR #Datascience https://hackernoon.com/how-netflix-works-the-hugely-simplified-complex-stuff-that-happens-every-time-you-hit-play-098632y4?source=rss\u00a0\u2026",
    },
    {
      account: {
        fullname: "Practical Programming \u00a0\ud83d\ude80 ProgramWithUs.com",
        href: "/ProgramWithUsNY",
        id: 797271725629173762,
      },
      date: "2020-03-24T17:00:00+07:00",
      hashtags: ["#programwithus", "#python"],
      likes: 0,
      replies: 0,
      retweets: 0,
      text:
        "check if patterns are match \n \n#programwithus #python  pic.twitter.com/xG9b5GzN0m",
    },
    {
      account: {
        fullname: "Samuel Williams",
        href: "/samLebro",
        id: 55426182,
      },
      date: "2020-03-24T16:31:00+07:00",
      hashtags: ["#Python", "#SelfTaughtProgrammer"],
      likes: 0,
      replies: 0,
      retweets: 0,
      text:
        "I love completing challenges. I would love to problem solve for a living. #Python #SelfTaughtProgrammer pic.twitter.com/W313VJk9QN",
    },
    {
      account: {
        fullname: "Leonardo Luduena",
        href: "/lle0x",
        id: 951196419444142081,
      },
      date: "2020-03-24T19:47:00+07:00",
      hashtags: ["#Python", "#DevOps"],
      likes: 0,
      replies: 0,
      retweets: 0,
      text:
        "#Page 2: Python for #DevOps: Python Scripting by Pranavi Pinky https://link.medium.com/Rj4ApWYd84\u00a0",
    },
    {
      account: {
        fullname: "OOI Ocean Data Lab",
        href: "/ooidatalab",
        id: 1082344206667005952,
      },
      date: "2020-03-24T19:40:00+07:00",
      hashtags: ["#Python", "#ocean", "#data"],
      likes: 0,
      replies: 0,
      retweets: 2,
      text:
        "To kick off our new #Python P-Tuesday series, check out our tutorial on how to create and model a simple seasonal timeseries. #ocean #data-analysis  https://datalab.marine.rutgers.edu/2020/03/modeling-seasonal-data/\u00a0\u2026 pic.twitter.com/IHiltqO7Yc",
    },
    {
      account: {
        fullname: "Ivan Leung",
        href: "/urganmax",
        id: 2345532612,
      },
      date: "2020-03-24T19:36:00+07:00",
      hashtags: ["#rmarkdown", "#python"],
      likes: 0,
      replies: 0,
      retweets: 0,
      text:
        "May I suggest #rmarkdown? It supports #python chunk, and I find it more flexible in terms of figure manipulation in final render.\n\n https://rstudio.github.io/reticulate/articles/r_markdown.html\u00a0\u2026",
    },
    {
      account: {
        fullname: "Python Flux",
        href: "/pythonbot_",
        id: 726709023563747328,
      },
      date: "2020-03-24T18:54:00+07:00",
      hashtags: ["#python", "#ad"],
      likes: 0,
      replies: 0,
      retweets: 0,
      text:
        "Machine Learning for Beginners: Absolute Beginner's Guide to Understanding Machine Learning, \
      Artificial Intelligence, Python Programming, Neural Networks Concepts and Big Data\
      https://zpy.io/5f3ee856\u00a0 #python #ad",
    },
    {
      account: {
        fullname:
          "Steven Jordan\u00a0\ud83d\udc0d\u00a0\ud83d\udc68\ud83c\udffb\u200d\ud83d\udcbb",
        href: "/thepydtyper",
        id: 759386987866578944,
      },
      date: "2020-03-24T18:13:00+07:00",
      hashtags: ["#code", "#python", "#Django", "#webdev", "#100DaysOfCode"],
      likes: 2,
      replies: 0,
      retweets: 0,
      text:
        "Past the 1200th line of #code today in this Taoism #python #Django #webdev project. Only about 20 more chapters more to go! #100DaysOfCode pic.twitter.com/Ryqe5opVto",
    },
    {
      account: {
        fullname: "DamagedDolphin",
        href: "/DamagedDolphin",
        id: 1108562583924011008,
      },
      date: "2020-03-24T17:47:00+07:00",
      hashtags: ["#RaspberryPi", "#Python"],
      likes: 7,
      replies: 0,
      retweets: 0,
      text:
        "Got a P2 display to replace my two P5 displays. So much sharper. I may go through and cleanup and comment my code finally to release it.\n#RaspberryPi #Python  pic.twitter.com/NdFXNeoI5B",
    },
    {
      account: {
        fullname: "\u15f0issy\u00a0\ud83c\udf40",
        href: "/CodeHer317",
        id: 986041095820795904,
      },
      date: "2020-03-24T17:39:00+07:00",
      hashtags: ["#Python", "#homework"],
      likes: 0,
      replies: 0,
      retweets: 0,
      text: "Playing with #Python #homework pic.twitter.com/ZD5HzCWTMv",
    },
    {
      account: {
        fullname: "Fullstack Developer",
        href: "/FullstackDevJS",
        id: 931055758971752448,
      },
      date: "2020-03-24T17:00:00+07:00",
      hashtags: [
        "#Fullstack",
        "#Javascript",
        "#Angular",
        "#DevTips",
        "#React",
        "#Php",
        "#Python",
        "#Rails",
        "#ROR",
        "#Datascience",
      ],
      likes: 20,
      replies: 0,
      retweets: 11,
      text:
        "How Netflix works: the (Hugely Simplified) Complex Stuff that Happens Every Time You Hit Play #Fullstack #Javascript #Angular #DevTips #React #Php #Python #Rails #ROR #Datascience https://hackernoon.com/how-netflix-works-the-hugely-simplified-complex-stuff-that-happens-every-time-you-hit-play-098632y4?source=rss\u00a0\u2026",
    },
    {
      account: {
        fullname: "Practical Programming \u00a0\ud83d\ude80 ProgramWithUs.com",
        href: "/ProgramWithUsNY",
        id: 797271725629173762,
      },
      date: "2020-03-24T17:00:00+07:00",
      hashtags: ["#programwithus", "#python"],
      likes: 0,
      replies: 0,
      retweets: 0,
      text:
        "check if patterns are match \n \n#programwithus #python  pic.twitter.com/xG9b5GzN0m",
    },
    {
      account: {
        fullname: "Samuel Williams",
        href: "/samLebro",
        id: 55426182,
      },
      date: "2020-03-24T16:31:00+07:00",
      hashtags: ["#Python", "#SelfTaughtProgrammer"],
      likes: 0,
      replies: 0,
      retweets: 0,
      text:
        "I love completing challenges. I would love to problem solve for a living. #Python #SelfTaughtProgrammer pic.twitter.com/W313VJk9QN",
    },
    {
      account: {
        fullname: "Leonardo Luduena",
        href: "/lle0x",
        id: 951196419444142081,
      },
      date: "2020-03-24T19:47:00+07:00",
      hashtags: ["#Python", "#DevOps"],
      likes: 0,
      replies: 0,
      retweets: 0,
      text:
        "#Page 3: Python for #DevOps: Python Scripting by Pranavi Pinky https://link.medium.com/Rj4ApWYd84\u00a0",
    },
    {
      account: {
        fullname: "OOI Ocean Data Lab",
        href: "/ooidatalab",
        id: 1082344206667005952,
      },
      date: "2020-03-24T19:40:00+07:00",
      hashtags: ["#Python", "#ocean", "#data"],
      likes: 0,
      replies: 0,
      retweets: 2,
      text:
        "To kick off our new #Python P-Tuesday series, check out our tutorial on how to create and model a simple seasonal timeseries. #ocean #data-analysis  https://datalab.marine.rutgers.edu/2020/03/modeling-seasonal-data/\u00a0\u2026 pic.twitter.com/IHiltqO7Yc",
    },
    {
      account: {
        fullname: "Ivan Leung",
        href: "/urganmax",
        id: 2345532612,
      },
      date: "2020-03-24T19:36:00+07:00",
      hashtags: ["#rmarkdown", "#python"],
      likes: 0,
      replies: 0,
      retweets: 0,
      text:
        "May I suggest #rmarkdown? It supports #python chunk, and I find it more flexible in terms of figure manipulation in final render.\n\n https://rstudio.github.io/reticulate/articles/r_markdown.html\u00a0\u2026",
    },
    {
      account: {
        fullname: "Python Flux",
        href: "/pythonbot_",
        id: 726709023563747328,
      },
      date: "2020-03-24T18:54:00+07:00",
      hashtags: ["#python", "#ad"],
      likes: 0,
      replies: 0,
      retweets: 0,
      text:
        "Machine Learning for Beginners: Absolute Beginner's Guide to Understanding Machine Learning, \
    Artificial Intelligence, Python Programming, Neural Networks Concepts and Big Data\
    https://zpy.io/5f3ee856\u00a0 #python #ad",
    },
    {
      account: {
        fullname:
          "Steven Jordan\u00a0\ud83d\udc0d\u00a0\ud83d\udc68\ud83c\udffb\u200d\ud83d\udcbb",
        href: "/thepydtyper",
        id: 759386987866578944,
      },
      date: "2020-03-24T18:13:00+07:00",
      hashtags: ["#code", "#python", "#Django", "#webdev", "#100DaysOfCode"],
      likes: 2,
      replies: 0,
      retweets: 0,
      text:
        "Past the 1200th line of #code today in this Taoism #python #Django #webdev project. Only about 20 more chapters more to go! #100DaysOfCode pic.twitter.com/Ryqe5opVto",
    },
    {
      account: {
        fullname: "DamagedDolphin",
        href: "/DamagedDolphin",
        id: 1108562583924011008,
      },
      date: "2020-03-24T17:47:00+07:00",
      hashtags: ["#RaspberryPi", "#Python"],
      likes: 7,
      replies: 0,
      retweets: 0,
      text:
        "Got a P2 display to replace my two P5 displays. So much sharper. I may go through and cleanup and comment my code finally to release it.\n#RaspberryPi #Python  pic.twitter.com/NdFXNeoI5B",
    },
    {
      account: {
        fullname: "\u15f0issy\u00a0\ud83c\udf40",
        href: "/CodeHer317",
        id: 986041095820795904,
      },
      date: "2020-03-24T17:39:00+07:00",
      hashtags: ["#Python", "#homework"],
      likes: 0,
      replies: 0,
      retweets: 0,
      text: "Playing with #Python #homework pic.twitter.com/ZD5HzCWTMv",
    },
    {
      account: {
        fullname: "Fullstack Developer",
        href: "/FullstackDevJS",
        id: 931055758971752448,
      },
      date: "2020-03-24T17:00:00+07:00",
      hashtags: [
        "#Fullstack",
        "#Javascript",
        "#Angular",
        "#DevTips",
        "#React",
        "#Php",
        "#Python",
        "#Rails",
        "#ROR",
        "#Datascience",
      ],
      likes: 20,
      replies: 0,
      retweets: 11,
      text:
        "How Netflix works: the (Hugely Simplified) Complex Stuff that Happens Every Time You Hit Play #Fullstack #Javascript #Angular #DevTips #React #Php #Python #Rails #ROR #Datascience https://hackernoon.com/how-netflix-works-the-hugely-simplified-complex-stuff-that-happens-every-time-you-hit-play-098632y4?source=rss\u00a0\u2026",
    },
  ],
};

export const mappedData = [
  {
    tweet: "#Page 1: Python Scripting by Pranavi Pinky https:/…",
    likes: "-",
    replies: "-",
    retweets: "-",
    hashtags: "#Python, #DevOps",
    date: "Mar 24, 2020",
  },
  {
    tweet: "To kick off our new #Python P-Tuesday series, chec…",
    likes: "-",
    replies: "-",
    retweets: 2,
    hashtags: "#Python, #ocean",
    date: "Mar 24, 2020",
  },
  {
    tweet: "May I suggest #rmarkdown? It supports #python chun…",
    likes: "-",
    replies: "-",
    retweets: "-",
    hashtags: "#rmarkdown, #python",
    date: "Mar 24, 2020",
  },
  {
    tweet: "Machine Learning for Beginners: Absolute Beginner'…",
    likes: "-",
    replies: "-",
    retweets: "-",
    hashtags: "#python, #ad",
    date: "Mar 24, 2020",
  },
  {
    tweet: "Past the 1200th line of #code today in this Taoism…",
    likes: 2,
    replies: "-",
    retweets: "-",
    hashtags: "#code, #python",
    date: "Mar 24, 2020",
  },
  {
    tweet: "Got a P2 display to replace my two P5 displays. So…",
    likes: 7,
    replies: "-",
    retweets: "-",
    hashtags: "#RaspberryPi, #Python",
    date: "Mar 24, 2020",
  },
  {
    tweet: "Playing with #Python #homework pic.twitter.com/ZD5…",
    likes: "-",
    replies: "-",
    retweets: "-",
    hashtags: "#Python, #homework",
    date: "Mar 24, 2020",
  },
  {
    tweet: "How Netflix works: the (Hugely Simplified) Complex…",
    likes: 20,
    replies: "-",
    retweets: 11,
    hashtags: "#Fullstack, #Javascript",
    date: "Mar 24, 2020",
  },
  {
    tweet: "check if patterns are match \n \n#programwithus #pyt…",
    likes: "-",
    replies: "-",
    retweets: "-",
    hashtags: "#programwithus, #python",
    date: "Mar 24, 2020",
  },
  {
    tweet: "I love completing challenges. I would love to prob…",
    likes: "-",
    replies: "-",
    retweets: "-",
    hashtags: "#Python, #SelfTaughtProgrammer",
    date: "Mar 24, 2020",
  },
  {
    tweet: "#Page 2: Python for #DevOps: Python Scripting by P…",
    likes: "-",
    replies: "-",
    retweets: "-",
    hashtags: "#Python, #DevOps",
    date: "Mar 24, 2020",
  },
  {
    tweet: "To kick off our new #Python P-Tuesday series, chec…",
    likes: "-",
    replies: "-",
    retweets: 2,
    hashtags: "#Python, #ocean",
    date: "Mar 24, 2020",
  },
  {
    tweet: "May I suggest #rmarkdown? It supports #python chun…",
    likes: "-",
    replies: "-",
    retweets: "-",
    hashtags: "#rmarkdown, #python",
    date: "Mar 24, 2020",
  },
  {
    tweet: "Machine Learning for Beginners: Absolute Beginner'…",
    likes: "-",
    replies: "-",
    retweets: "-",
    hashtags: "#python, #ad",
    date: "Mar 24, 2020",
  },
  {
    tweet: "Past the 1200th line of #code today in this Taoism…",
    likes: 2,
    replies: "-",
    retweets: "-",
    hashtags: "#code, #python",
    date: "Mar 24, 2020",
  },
  {
    tweet: "Got a P2 display to replace my two P5 displays. So…",
    likes: 7,
    replies: "-",
    retweets: "-",
    hashtags: "#RaspberryPi, #Python",
    date: "Mar 24, 2020",
  },
  {
    tweet: "Playing with #Python #homework pic.twitter.com/ZD5…",
    likes: "-",
    replies: "-",
    retweets: "-",
    hashtags: "#Python, #homework",
    date: "Mar 24, 2020",
  },
  {
    tweet: "How Netflix works: the (Hugely Simplified) Complex…",
    likes: 20,
    replies: "-",
    retweets: 11,
    hashtags: "#Fullstack, #Javascript",
    date: "Mar 24, 2020",
  },
  {
    tweet: "check if patterns are match \n \n#programwithus #pyt…",
    likes: "-",
    replies: "-",
    retweets: "-",
    hashtags: "#programwithus, #python",
    date: "Mar 24, 2020",
  },
  {
    tweet: "I love completing challenges. I would love to prob…",
    likes: "-",
    replies: "-",
    retweets: "-",
    hashtags: "#Python, #SelfTaughtProgrammer",
    date: "Mar 24, 2020",
  },
  {
    tweet: "#Page 3: Python for #DevOps: Python Scripting by P…",
    likes: "-",
    replies: "-",
    retweets: "-",
    hashtags: "#Python, #DevOps",
    date: "Mar 24, 2020",
  },
  {
    tweet: "To kick off our new #Python P-Tuesday series, chec…",
    likes: "-",
    replies: "-",
    retweets: 2,
    hashtags: "#Python, #ocean",
    date: "Mar 24, 2020",
  },
  {
    tweet: "May I suggest #rmarkdown? It supports #python chun…",
    likes: "-",
    replies: "-",
    retweets: "-",
    hashtags: "#rmarkdown, #python",
    date: "Mar 24, 2020",
  },
  {
    tweet: "Machine Learning for Beginners: Absolute Beginner'…",
    likes: "-",
    replies: "-",
    retweets: "-",
    hashtags: "#python, #ad",
    date: "Mar 24, 2020",
  },
  {
    tweet: "Past the 1200th line of #code today in this Taoism…",
    likes: 2,
    replies: "-",
    retweets: "-",
    hashtags: "#code, #python",
    date: "Mar 24, 2020",
  },
  {
    tweet: "Got a P2 display to replace my two P5 displays. So…",
    likes: 7,
    replies: "-",
    retweets: "-",
    hashtags: "#RaspberryPi, #Python",
    date: "Mar 24, 2020",
  },
  {
    tweet: "Playing with #Python #homework pic.twitter.com/ZD5…",
    likes: "-",
    replies: "-",
    retweets: "-",
    hashtags: "#Python, #homework",
    date: "Mar 24, 2020",
  },
  {
    tweet: "How Netflix works: the (Hugely Simplified) Complex…",
    likes: 20,
    replies: "-",
    retweets: 11,
    hashtags: "#Fullstack, #Javascript",
    date: "Mar 24, 2020",
  },
];
